### ISSUE TITLE
Add support for className attribute

### ISSUE THREAD

**Issue by smetzdev** [lightyen/vscode-tailwindcss-twin#7]
Hello, 

if not already working and since twin.macro is also allowing this options, i think it would be nice if the suggestions worked inside the className attribute, too

**Comment by lightyen** [comment]
No, i won't add this feature, because this function in twin.macro is unclear.
```js
<div className="my-0 my-style" />
```
- How do i know whether `my-0` or `my-style` is custom class or really exists?
- How do i make diagnostics of them?
- Why twin respond an error about `my-style` to me?

I agree with *twin.macro* on using **className** prop to integrate some components base on tailwindcss, but i don't think that developing something with this is a good idea.

**Comment by smetzdev** [comment]
Okay, i understand. Thanks for the feedback
